import Link from "next/link";
import React from "react";
const getPosts = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts");
  const data = await res.json();
  return data;
};

export const metadata = {
  title: "Pst API data | Learning nextjs ",
  description: "Generated by create next app",
};

const page = async () => {
  const data = await getPosts();
  return (
    <div className="grid grid-cols-3 gap-4">
      {data.map((d) => (
        <div key={d.id}>
          <p>{d.title}</p>
          <p>{d.body}</p>
          <Link href={`posts/${d.id}`}>
            <p className="text-green-500">Details</p>{" "}
          </Link>
        </div>
      ))}
    </div>
  );
};

export default page;
